from kokoro import KPipeline
import soundfile as sf

pipeline = KPipeline(lang_code="a")

text = """
Hello! This is the first voice generated by Anvora AI.
"""

generator = pipeline(
    text,
    voice="af_heart",
)

audio = []

for _, _, samples in generator:
    audio.extend(samples)

sf.write("test.wav", audio, 24000)

print("✅ Voice generated: test.wav")